### ISSUE TITLE
doc error?: http://www.urbit.org/2013/11/18/urbit-is-easy-ch5.html :: IEEE section

### ISSUE THREAD

**Issue by bshanks** [urbit/archaeology#110]
In http://www.urbit.org/2013/11/18/urbit-is-easy-ch5.html , in section "IEEE single-precision", in the example, on the second line, it says

```
.-6.2832            ::  -τ as @
```

perhaps what was meant was

```
.-6.2832            ::  -τ as @rs
```

?

**Comment by cgyarvin** [comment]
Good catch, thanks!
