### ISSUE TITLE
Leaking the names of directories we watch

### ISSUE THREAD

**Issue by mrdomino** [urbit/archaeology#127]
Probably a libuv bug? "leaks vere" on OS X shows 54 leaks for 4944 leaked bytes. Each leak is the full UNIX path to a watched dir.

**Comment by cgyarvin** [comment]
This probably happened in the recent Inotify fix...

**Comment by ghost** [comment]
Running a checkout before that fix still shows the leak.

**Comment by mrdomino** [comment]
It's possible that this was an older leak -- I remember seeing something similar back in December when I first started chasing leaks, but I didn't see it in a run of `leaks` a while back on a now-unknown commit.

I wouldn't worry too much about it for now. It's probably libuv's fault.

**Comment by cgyarvin** [comment]
Probably my fault I suspect. I'll look at it tomorrow if no one does today.
