### ISSUE TITLE
vere: f/rail.c:1983: u2_rl_cell: Assertion `1 == u2_rl_junior(ral_r, b)' failed.

### ISSUE THREAD

**Issue by ngvrnd** [urbit/archaeology#128]
did a git pull origin master && make clean all, fired up a submarine, did some poking about with odors and types and such, then, while I was typing notes about what I'd learned, the submarine crashed:

~pinlut-nosrux-bottec-rigmun--tilfex-banwed-sittex-fondut/try=> 
vere: f/rail.c:1983: u2_rl_cell: Assertion `1 == u2_rl_junior(ral_r, b)' failed.
[1]    4519 abort (core dumped)  bin/vere fnord

**Comment by ngvrnd** [comment]
This is on a DO droplet running some recent flavor of ubuntu

➜  urbit git:(master) ✗ uname -a
Linux bitmet 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:12:00 UTC 2013 i686 i686 i686 GNU/Linux
➜  urbit git:(master) ✗ cat /etc/debian_version 
wheezy/sid

**Comment by ngvrnd** [comment]
Because, as my father used to say, I "... don't know when to stop ...", I fired that sub back up to see what would happen, because, hey, submarine, and applying the previous observation regarding my restraint, I tried some stuff:

~pinlut-nosrux-bottec-rigmun--tilfex-banwed-sittex-fondut/try=> =foo (add 1 1)
~pinlut-nosrux-bottec-rigmun--tilfex-banwed-sittex-fondut/try=> -:!>(foo)
out of memory

out of memory

vere: f/rail.c:597: _rl_bloq_grab: Assertion `( (('k') << 24) | ( (('c') << 16) | ( (('o') << 8) | ( ('r') ) ) ) ) == *(((c3_w *)0x404db000) + (((ral_r) + ( ((c3_w *)&((u2_loom_rail *)0)->hip_m) - ((c3_w *)0) ) )))' failed.
[1]    4600 abort (core dumped)  bin/vere fnord

I dunno if this is an aspect of the first problem, or a separate bug, or just an everyday goring-on-the-sharp-edges-of-my-dream-kitchen.  Please advise.  I will gladly file a separate bug.

**Comment by ngvrnd** [comment]
oops.

**Comment by cgyarvin** [comment]
Nick, do you have either a reproduction procedure or a stack trace? This is almost certainly introduced in one of the recent system level changes. But we can't do much without one of these things.

**Comment by ngvrnd** [comment]
Well... the out of memory thing is quite reproducible, but the first case... not so much.  I will try at lunch to carefully repeat the steps that led up to it, and report back.

**Comment by ngvrnd** [comment]
Just tried, using command line recall.  So far, no crash.  I looked for core files since it said "core dumped" but it seems to have been lying. Should I do a debug build and run under gdb?

**Comment by cgyarvin** [comment]
The crash in -:!>((add 1 1)) is just because you're effectively trying to
print the entire kernel.  It doesn't frighten me, much.  It is also
reproducible.

I am much more interested in the other core.  If it said "core dumped," it
dumped a core.  Maybe in /cores?

**Comment by ngvrnd** [comment]
So, I did a "sudo find / -name core" and nothing that came up looked
relevant.

Oh farg.  I just learned a whole bunch of stuff I didn't want to know about
ubuntu.

Ubuntu has this thing called apport, which is responsible for those
friendly pop-ups saying "Your program has crashed, would you like to send a
report?" etc.

And one of the other features of apport is it eats all your core files in
the process of writing these crash reports.  I have not succeeded in
finding out what it did, exactly, with that core file, but I'm still
looking.

**Comment by cgyarvin** [comment]
@has a strong desire to bugger Mark Shuttleworth.

**Comment by ngvrnd** [comment]
On Wed, Mar 26, 2014 at 1:44 PM, cgyarvin notifications@github.com wrote:

> @has a strong desire to bugger Mark Shuttleworth.

Well, this isn't going to reduce that...

OK.  So if you look at

/proc/sys/kernel/core_pattern

you find out the file name the core file is written to.

Under pere ubu, 13.10, it is set to this:

|/usr/share/apport/apport %p %s %c

Yes, folks, the file is ... a pipe to this apport thing.  Which thing is
responsible for sending bug reports to maintainers of packages.

In /var/log/apport.log, I find

ERROR: apport (pid 4713) Wed Mar 26 09:52:19 2014: executable:
/home/nzc/urbit/bin/vere (command line "bin/vere fnord")
ERROR: apport (pid 4713) Wed Mar 26 09:52:19 2014: executable does not
belong to a package, ignoring

And, FWIW, ulimit -c was 0.  Some say that, if you ulimit -c <large> you
will get a core file even with apport running, but others say, no.

:-(

We need a minimal linux to run on these cloud servers.  Ubuntu is... not
positioned for this kind of work.

**Comment by ghost** [comment]
Try:

```
ulimit -c unlimited; sudo sysctl -w kernel.core_pattern=core
```

**Comment by ngvrnd** [comment]
Will do.  I'm investigating running arch linux as well, as it at least claims to be a minimalist base install...

**Comment by mrdomino** [comment]
Arch is pretty minimalist, but that doesn't stop it from sending corefiles to systemd-coredump.

On that note, I believe I'll have one the next time macmud crashes.

**Comment by mrdomino** [comment]
Here we go:

```
#0  0x00007f08d7d2b389 in raise () from /usr/lib/libc.so.6
#1  0x00007f08d7d2c788 in abort () from /usr/lib/libc.so.6
#2  0x00007f08d7d244a6 in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007f08d7d24552 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00000000004214e8 in u2_rl_cell (ral_r=0, a=0, b=2876217768) at f/rail.c:1983
#5  0x000000000042f8bb in u2_bn_cell (wir_r=0, a=0, b=2876217768) at f/bail.c:288
#6  0x000000000042a488 in u2_cn_cell (a=0, b=2876217768) at f/coal.c:707
#7  0x000000000040abc9 in _http_request (req_u=0x109d6e0) at v/http.c:855
#8  0x000000000040a186 in _http_message_complete (par_u=0x10b8590) at v/http.c:490
#9  0x000000000045fe3f in http_parser_execute (parser=0x10b8590,
    settings=0x693f20 <_http_settings>,
    data=0x10da960 "GET http://proxyjudge1.proxyfire.net/fastenv HTTP/1.1\r\nHost: proxyjudge1.proxyfire.net\r\nUser-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)\r\nAccept: */*\r\nAccept-Language: en-us"..., len=228)
    at outside/jhttp/http_parser.c:1620
```

**Comment by cgyarvin** [comment]
I was treating an IP address as a noun, which works fine unless its high bit is set.
