### ISSUE TITLE
Assertion failed when starting vere

### ISSUE THREAD

**Issue by franc0is** [urbit/archaeology#129]
My laptop crashed while vere was executing. Since then, I am unable to run vere.

```
$ ./bin/vere pier1
vere: urbit home is /Users/francois/Sources/urbit/urb
vere: hostname is francois-mbp.local
loom: loaded 21MB
init: gc: 10.977.120 bytes live
time: ~2014.4.4..23.13.45..ee62
raft: single-instance mode
raft:      -> lead
sist: booting
rest: checkpoint to event 5.220
rest: old 0v5.u24jg, new 0v1t.h6uq5
loaded passcode from /Users/francois/.urbit/~sicmug-tiptux.txt

Assertion failed: ((las_w + 1) == old_w), function _sist_rest, file v/sist.c, line 1001.
Abort trap: 6 (core dumped)
```

I can provide the contents of my pier if required.

**Comment by cgyarvin** [comment]
Yikes!  We'll take a look at it.

**Comment by ghost** [comment]
What git version are you running? (the first line of `git show` should tell you)

**Comment by franc0is** [comment]
commit 471c3a5f43650c9a85204308a709a0e1b9c4b1b0
Author: ~hatteb-mitlyd anthony@tlon.io
Date:   Thu Apr 3 14:47:22 2014 -0700

```
remove the old poll-based term stuff in favor of a uv_pipe
```

**Comment by ghost** [comment]
Seconding Curtis - yikes!

Send me (anthony@tlon.io) your pier, urb/shipname, and passcode file and I'll have a look. You might also have a core in /cores - add that if so.

**Comment by ghost** [comment]
It looks like the checkpoint loaded more events than the event log has in it. Unfortunately, that's all I can gather.

```
(lldb) p $r15
(unsigned long) $5 = 5218
(lldb) p u2_Host.arv_u->ent_w
(c3_w) $6 = 5220
```

**Comment by ghost** [comment]
No repro…
