### ISSUE TITLE
Crash loading /gen/try/web/simple.html on fresh destroyer

### ISSUE THREAD

**Issue by mrdomino** [urbit/archaeology#135]
The crash is on 1108:15 of eyre.hoon. Happens with the most recent eyre on a totally stock, freshly created destroyer with nothing fancy going on.

**Comment by mrdomino** [comment]
Incidentally, complete.html and hello.html both load fine. The problem only appears for simple.html. It happens both from http://labtud-machep.urbit.org/gen/try/web/simple.html and from http://localhost:8080/labtud-machep/gen/try/web/simple.html.

**Comment by ghost** [comment]
It looks like "epic" is no longer the right function to use in `/=try=/syn/web/simple/htmn/hoon`. If you change it to `give` it works.
