### ISSUE TITLE
vere/arvo takes forever to launch

### ISSUE THREAD

**Issue by charliegreen** [urbit/archaeology#138]
I'm not sure if this is actually an issue or if I'm just really impatient, but I ran `$ bin/vere mypier` about half an hour ago, and it's been eating up 100% CPU this whole time. This is its output:

```
charlie@asimov:~/dev/urbit$ bin/vere mypier
vere: urbit home is /home/charlie/dev/urbit/urb
≜
welcome.
vere: hostname is asimov
loom: loaded 11MB
init: gc: 6.790.272 bytes shed; 2.756 bytes live
```

It's been a while since I've done anything with Urbit; is it just taking a long time to start back up, or is there an actual issue? I did `$ git pull origin master` and ran `$ make`.

Thank you!

**Comment by cgyarvin** [comment]
Yes, your pier is too old - you need to create a new one with -c and then
recreate your destroyer.

**Comment by charliegreen** [comment]
Awesome, thank you!
