### ISSUE TITLE
Raspberry PI

### ISSUE THREAD

**Issue by davidmnoriega** [urbit/archaeology#140]
I was able to compile it on a raspberry pi, but when it came time to run vere, it segfaults. Looks like it wants 1024MB of memory, but a pi only has 512MB.

**Comment by cgyarvin** [comment]
Yeah that's unfortunate - for one thing it's way too rigid.  We are doing
an update of the memory system soon.  It really should be possible to run
urbit just fine in 512MB.  I was born in the 18th century so this still
seems like a lot to me...

**Comment by cgyarvin** [comment]
I am not sure this is the only issue, I haven't tried recently, but if I 
did a bisect I could show you the commit where vere stopped working on my 
TF700T (another arm)

Actually I think it was the day that re2 dependency was added...

**Comment by cgyarvin** [comment]
Ah, that is interesting... and not terribly surprising.  Does it also
reflect itself as memory exhaustion?  That would be a strange correlation
with re2.... but that's a fairly phat jet.  And then, you know, C++...

**Comment by davidmnoriega** [comment]
This is the exact output

```
pi@raspberrypi:~/workspace/urbit$ ./bin/vere -c mypier
vere: urbit home is /home/pi/workspace/urbit/urb
≜
welcome.
vere: hostname is raspberrypi
loom: mapped 1024MB
loading /home/pi/workspace/urbit/urb/urbit.pill
address (nil) out of loom!
Segmentation fault (core dumped)
```

**Comment by cgyarvin** [comment]
Any way you can pull a stacktrace on that?

**Comment by davidmnoriega** [comment]
Like this?

```
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `./bin/vere -c mypier'.
Program terminated with signal 11, Segmentation fault.
#0  u2_na_put (nas_u=0xad7090, key=39, val=0x1) at f/nash.c:75
75        if ( 0 == buc_u->con_w ) {
(gdb) bt
#0  u2_na_put (nas_u=0xad7090, key=39, val=0x1) at f/nash.c:75
#1  0x00023024 in _cue_in (wir_r=0, a=<optimized out>, b=39)
    at gen164/5/cue.c:25
#2  0x00023168 in _cue_in (wir_r=0, a=2181039581, b=35) at gen164/5/cue.c:40
#3  0x00023168 in _cue_in (wir_r=0, a=2181039581, b=26) at gen164/5/cue.c:40
#4  0x00023124 in _cue_in (wir_r=0, a=2181039581, b=24) at gen164/5/cue.c:38
#5  0x00023168 in _cue_in (wir_r=0, a=2181039581, b=14) at gen164/5/cue.c:40
#6  0x00023124 in _cue_in (wir_r=0, a=2181039581, b=12) at gen164/5/cue.c:38
#7  0x00023168 in _cue_in (wir_r=0, a=2181039581, b=2) at gen164/5/cue.c:40
#8  0x00023124 in _cue_in (wir_r=0, a=2181039581, b=0) at gen164/5/cue.c:38
#9  0x0002328c in j2_k_164__mood__hoon__cue_my (wir_r=0, a=2181039581)
    at gen164/5/cue.c:77
#10 0x00017df0 in u2_cke_cue (a=2181039581) at f/coal.c:964
#11 0x0004a518 in u2_reck_cold (rec_u=0x424db240, kno_w=<optimized out>)
    at v/reck.c:412
#12 0x0004a84c in u2_reck_boot (rec_u=0x4a84c) at v/reck.c:951
#13 0x0000e634 in main (argc=<optimized out>, argv=0xe634) at v/main.c:370
```

**Comment by cgyarvin** [comment]
That definitely helps.  The RPI seems allergic to our new internal hash
library...

**Comment by ghost** [comment]
Unfortunately, this does appear to be an allergy to the trie code. Grr argh.

**Comment by cgyarvin** [comment]
Urbit now works on the RasPi again.  The problem was an upstream bug in the
trie search library we've been using.  Thanks to David for calling it to
our attention and ~hatteb-mitlyd for fixing it...
