### ISSUE TITLE
Homebrew formula [discussion]

### ISSUE THREAD

**Issue by dcow** [urbit/archaeology#141]
I'm working on a `brew` formula for Urbit.  Nothing too complicated, but I have com across a few discussion topics.
-  Because `vere` requires `URBIT_HOME` to be set, the formula must either:
  1.  show the user the location of `URBIT_HOME` and instruct them to add the environment variable manually,
  2.  patch the installation to include a wrapper script that sets up and tears down the environment before and after executing `vere`, respectively, or
  3.  attempt to automatically add the variable to the underlying system's default environment during the install process.
     I'm leaning towards option **ii** right now.
-  There is no install option in the Makefile as is.  I can
  1.  add an install option to the Makefile, or
  2.  perform the install steps manually during the install phase of the formula.
     Option **i** is reusable by other package managers in the future, but option **ii** wouldn't require modifications to the Makefile.
-  Is there any special consideration for the `outside` directory?  Or can this be discarded after the build has finished?  Should all of the source simply be discarded?

Here's how I imagine the directories mapping out:

| Project Location | Installed Location<sup>*</sup> |
| --- | --- |
| bin/vere | bin/vere |
| extras | share/extras |
| f | src/f |
| include | include |
| outside |  |
| Spec | share/Spec |
| urb | opt/urbit |
| v | src/v |

<sup>*</sup>Installed locations are prefaced by the `brew` install prefix.

And `URBIT_HOME` becomes something like: /usr/local/opt/urbit

I figure someone may have a more directed understanding of the project; does this look sane?  And, any comments regarding which strategy might be best for handling the actual install?

**Comment by jhance** [comment]
Whats wrong with

URBIT_HOME=<> bin/vere

in a shell script that runs the real vere

By the way, I don't think URBIT_HOME is even used within newbreach.

**Comment by cgyarvin** [comment]
Good news - URBIT_HOME is gone in the next release!

**Comment by dcow** [comment]
Good news indeed!  Any thoughts on the install procedure (_add to make_ versus _perform via package install script_)?

**Comment by ghost** [comment]
With the new regime, you can do something like "make LIB=/wherever/homebrew/wants/it" and then copy the urb/ directory there however you like.
