### ISSUE TITLE
Demonstration Web server doesn't function (can't find Hume library)

### ISSUE THREAD

**Issue by andrew-hoffman** [urbit/archaeology#17]
Found this issue at the end of the Arvo tutorial.

```
=>  .(+ =>(+ ^/=main=/hume))
```

in /try/bin/fgame.hoon needs to be changed to

```
=>  .(+ =>(+ ^/=main=/lib/hume))
```

to match the other references to hume elsewhere in the codebase, otherwise the server prints an unhelpful message of the form

```
~ /cx/~tapmes-nissul-dozsud-martex--rivsyt-sigtyv-witlyr-poclyd/main/~2013.9.25..04.46.29..d786/hume/hoon
```

and returns to the prompt.
I assume that Hume is the Hoon standard library by the comment on the top of that file, and that it was moved and not everything was updated to reflect this. I can't tell if this file is created from one of the two copies in the repository or synchronized over the network.

**Comment by cgyarvin** [comment]
Yes, that file missed out on one of my great updates.  I'll fix it when I
get unswamped...

**Comment by andrew-hoffman** [comment]
guess this was fixed by cdcarter.
