### ISSUE TITLE
Build doesn't link to ncurses (Slackware)

### ISSUE THREAD

**Issue by philipcmonk** [urbit/archaeology#21]
On Slackware64 14.0, make fails complaining that it isn't linked with some of the ncurses functions.  Adding "-lcurses" onto the end of line 42 of the Makefile (defining OSLIBS for linux) solves the problem.

**Comment by cgyarvin** [comment]
Hm don't think it will break anything.  Can you send a pull?

**Comment by philipcmonk** [comment]
Sure, no problem.
