### ISSUE TITLE
Gross system failure: tegra2/KatKiss (Transformer TF101)

### ISSUE THREAD

**Issue by yebyen** [urbit/archaeology#26]
I have worked past my udp port mapping issue which seems to be caused by not having root (?) on my ARM machine, a Transformer TF-101

Now I am getting a "Gross system failure" which is an exceptional error message

You can prioritize fixing this as very low, I'd like to have time to figure it out for myself since I should be able to trace back and tell more about what's happening on my particular system better than someone else

I have mapped enough memory as swap, I don't know what it could be needing 1024MB for, but I suspect someone else will have had this issue before long...

Here is the precise output (from saucy chroot, not from precise):

```
yebyen@localhost:~/urbit$ sudo bin/vere -c hono
vere: urbit home is /home/yebyen/urbit
loom: mapped 1024MB
/home/yebyen/urbit/urbit.pill: No such file or directory
hono: gc: 776 bytes live
bin/vere: gross system failure
```

**Comment by abliss** [comment]
Looks like you might've skipped this step in Chapter 1:

echo "export URBIT_HOME=`pwd`/urb" >>~/.bash_profile
source ~/.bash_profile

**Comment by yebyen** [comment]
That's just what I thought, but:

yebyen@localhost:~/urbit/urb$ echo $URBIT_HOME
/home/yebyen/urbit/urb

**Comment by abliss** [comment]
Ah, yes, you're using sudo, which seems to be dumping your env.

Try `sudo URBIT_HOME=/home/yebyen/urbit/urb bin/vere -c hono`

**Comment by yebyen** [comment]
It's sudo, unmapping my environment variables and not sourcing anything.

**Comment by yebyen** [comment]
Thanks!

**Comment by yebyen** [comment]
And having root didn't solve v/ames.c:306
