### ISSUE TITLE
Remove old items from the directory tree

### ISSUE THREAD

**Issue by ghost** [urbit/archaeology#29]
So this one time on the developer mailing list, @ericfode was all like, "WTF is all this weird stuff in the directory tree?", and @cgyarvin was like, "Wow, we really need to get all the ancient stuff out of the repository."

So I'm like, let's make a GitHub issue so we'll remember, and also so that curious onlookers will see that we're aware of the problem and will fix it. Eventually.

**Comment by cdcarter** [comment]
See PR #30.

If anyone smarter than me wants to make sure there are no excess includes, or wants to try and clean up Spec/ please pile on.

**Comment by cdcarter** [comment]
I think this can probably be closed now? I've deleted every full file that isn't necessary to build.
