### ISSUE TITLE
`add` restricted to three-digit integers

### ISSUE THREAD

**Issue by Walther** [urbit/archaeology#39]
[The introduction](http://www.urbit.org/2013/08/22/Chapter-1-arvo.html) mentions in the examples the following:

> Two, you called the Hoon add function to see that two plus two is four. Math seems to work the same on the off-world colonies.

~~However, the `add` function works on integer pairs up to three digits each - with the maximum at `(add 999 999)` with the result of `1.998`~~

I think ~~either~~
- ~~this limitation should be removed, or~~
- the tutorial needs clarification ~~on why this restriction exists~~

**Comment by cgyarvin** [comment]
The syntax for decimal integers is the German syntax, with dots every three digits.
