### ISSUE TITLE
vere binary finds wrong $URBIT_HOME

### ISSUE THREAD

**Issue by jacoblyles** [urbit/archaeology#47]
I'm running through the initial setup on Mac. 

`echo $URBIT_HOME` gives `/Users/jacob/code/urbit/urbit/urb`, which is correct. 

When I run `bin/vere -c mypier` I get

```
vere: urbit home is /Users/jacob/urbit
loom: mapped 1024MB
/Users/jacob/urbit/urbit.pill: No such file or directory
mypier: gc: 548 bytes live
bin/vere: gross system failure
```

**Comment by cgyarvin** [comment]
Looks like you didn't export.
