### ISSUE TITLE
Destroyer Problem

### ISSUE THREAD

**Issue by pgray** [urbit/archaeology#49]
When trying to start a destroyer I am getting a "not responding still trying" message followed by [waiting...].

I'm not sure if I did something wrong, but the tutorial says to follow the directions and that seems to be getting me nowhere.

Any help would be much appreciated if this isn't a real issue.

**Comment by johncburnham** [comment]
Can you paste your terminal output?

**Comment by cgyarvin** [comment]
I can tell you that the server (~zod) is very much up right now - but if it
says it's down, the overall probability is that it's down...

**Comment by pgray** [comment]
Form: %anon
generating 2048-bit RSA key...
[waiting...]

is what I get to and then it sits there for what seems like an unreasonable amount of time.

If I hit enter it exits and spits out:

! \//~midrev-banwet-finsyt-ritsur--tagfes-matpun-mitrep-wisrem/main/~2013.10.4..23.28.53\/
!   ..03fb/lib/pony/:<[52 3].[63 5]>
! \/                                                                                    \/
! \//~midrev-banwet-finsyt-ritsur--tagfes-matpun-mitrep-wisrem/main/~2013.10.4..23.28.53\/
!   ..03fb/lib/pony/:<[53 3].[63 5]>
! \/                                                                                    \/
! \//~midrev-banwet-finsyt-ritsur--tagfes-matpun-mitrep-wisrem/main/~2013.10.4..23.28.53\/
!   ..03fb/lib/pony/:<[53 16].[53 18]>
! \/                                                                                    \/
! exit

**Comment by twopir** [comment]
I've done `:begin` from a new machine, entered a ship and a ticket, and now have a similar issue reaching doznec. I haven't tried hitting Enter, since I figure that kills the current task.

```
generating 2048-bit RSA key...
; ~doznec _Urban Republic_ is your neighbor
; ~doznec _Urban Republic_ is your neighbor
request approved
~holrus-marfun-roctux-lavmul--rapmyr-labreg-nopwed-nilbud/try=> 
; ~doznec not responding still trying
[waiting...]
```

I haven't tried using a different ship/ticket yet.

**Comment by twopir** [comment]
Using a different ship/ticket appeared to work.

**Comment by cgyarvin** [comment]
John, can you check that we didn't double-issue here? Mistakes happen...

**Comment by twopir** [comment]
Do you need the name of the ship I tried to `:begin`? If so, can I `:hi` it to you from my new destroyer?

**Comment by johncburnham** [comment]
yes the ship name would be helpful. :hi me at ~tomsyt-balsen

**Comment by ericfode** [comment]
@twopir @cgyarvin @johncburnham Anyone mind if I close this?

**Comment by pgray** [comment]
Should be ok. I think it might have been resolved by rebuilding the pier.
