### ISSUE TITLE
Arvo build instructions, OSX/macports

### ISSUE THREAD

**Issue by cgyarvin** [urbit/archaeology#5]

**Comment by johncburnham** [comment]
ugh, macports. arguably we can just do homebrew and if someone feels passionately about macports they can translate the instructions themselves

**Comment by cgyarvin** [comment]
Ok fine, teh lazy can win this time :-)

**Comment by johncburnham** [comment]
yeah yeah.... fine, I'll do macports last. It's clearly a P3.

**Comment by cgyarvin** [comment]
Yes.  And, also, if you think it's easier to skip the make instructions and
just set up the damn packages... it's not really a locus of wasted work
because I don't think we're going to add any libraries, etc, at this point.

**Comment by johncburnham** [comment]
You know, that's a good point. I'll get on it.

**Comment by agentultra** [comment]
Just need to change the include/lib paths to /opt/local/... instead of /usr for macports
