### ISSUE TITLE
Segfaults on OSX10.5.8

### ISSUE THREAD

**Issue by davids99us** [urbit/archaeology#52]
David-Stockwells-Computer-2:urbit-master davids$ bin/vere -c mypier 
vere: urbit home is /Users/davids/urbit-master/urb
loom: mapped 1024MB
time: ~2013.10.7..01.45.52..badb
ames: on localhost, UDP 49653.
http: live on 8080
generating 2048-bit RSA pair...
address 0x0 out of loom!
Segmentation fault
David-Stockwells-Computer-2:urbit-master davids$ 

Mac OSX 10.5.8
1.67 GHz Power PC G4
1 GB mem

All good  with macports install up to there.  Downloaded the master zip file as git doesn't support the architecture. Is this the latest version?

**Comment by cgyarvin** [comment]
Ooh that's a G4. Never tried it on one... Can you get a stack trace tho?

**Comment by davids99us** [comment]
Is this it?

Process:         vere [23401]
Path:            bin/vere
Identifier:      vere
Version:         ??? (???)
Code Type:       PPC (Native)
Parent Process:  bash [23054]

Date/Time:       2013-10-07 11:46:29.761 +1000
OS Version:      Mac OS X 10.5.8 (9L31a)
Report Version:  6
Anonymous UUID:  DF8ABA10-81FF-41EF-A81F-2550204ED487

Exception Type:  EXC_CRASH (SIGSEGV)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Crashed Thread:  0

Thread 0 Crashed:
0   libSystem.B.dylib             0x96f5a9f0 __kill + 12
1   libsigsegv.2.dylib             0x0023d800 terminating_handler + 16
2   libSystem.B.dylib             0x96f153bc realpath$DARWIN_EXTSN + 152
3   vere                           0x0006bd3c uv__fsevents_init + 88
(fsevents.c:221)
4   vere                           0x0006b4a8 uv_fs_event_init + 488
(kqueue.c:321)
5   vere                           0x0000f980 _unix_hot_gain + 272
6   vere                           0x0000fa14 u2_unix_ef_init + 52
7   vere                           0x00009e14 u2_reck_kick + 1652
8   vere                           0x00005c24 _lo_sure + 308
9   vere                           0x00006aa4 _lo_work + 756
10  vere                           0x00007b44 u2_lo_loop + 676
11  vere                           0x000088f8 main + 1944
12  vere                           0x00002560 start + 64

Thread 1:
0   libSystem.B.dylib             0x96ed9078 mach_msg_trap + 8
1   libSystem.B.dylib             0x96edff9c mach_msg + 56
2   libsigsegv.2.dylib             0x0023d570 mach_exception_thread + 76
3   libSystem.B.dylib             0x96f1af70 _pthread_start + 316

Thread 2:
0   libSystem.B.dylib             0x96ed9078 mach_msg_trap + 8
1   libSystem.B.dylib             0x96edff9c mach_msg + 56
2   com.apple.CoreFoundation       0x919f0394 CFRunLoopRunSpecific + 1812
3   com.apple.CoreFoundation       0x919f0c1c CFRunLoopRun + 60
4   vere                           0x00069244 uv__cf_loop_runner + 132
(darwin.c:119)
5   vere                           0x0006771c uv__thread_start + 80
6   libSystem.B.dylib             0x96f1af70 _pthread_start + 316

Thread 0 crashed with PPC Thread State 32:
  srr0: 0x96f5a9f0  srr1: 0x0000d030   dar: 0xf0102ee4 dsisr: 0x42000000
    r0: 0x00000025    r1: 0xbfffa670    r2: 0x0000008d    r3: 0x00000000
    r4: 0x00000000    r5: 0x00000001    r6: 0x2d746963    r7: 0x64656d00
    r8: 0xffb68180    r9: 0x00000000   r10: 0xffffffc1   r11: 0xa0b1052c
   r12: 0x96f5a9dc   r13: 0x00000000   r14: 0x00000000   r15: 0xbfffc4e8
   r16: 0x000778b0   r17: 0x000778b0   r18: 0x00000000   r19: 0x00000000
   r20: 0x000867c0   r21: 0x0012a670   r22: 0x00000000   r23: 0x8216af7d
   r24: 0x0007f880   r25: 0x00000000   r26: 0x00497ca0   r27: 0x00497ca1
   r28: 0x0012a044   r29: 0x00497db0   r30: 0x00497e80   r31: 0x96f15338
    cr: 0x42000222   xer: 0x00000004    lr: 0x0023d804   ctr: 0x96f5a9dc
vrsave: 0x00000000

Binary Images:
    0x1000 -    0x74ff3 +vere ??? (???) <3c05ca9e2d705bcc78367cba005a89d9>
/Users/davids/urbit-master/bin/vere
  0x189000 -   0x1e0fef +libgmp.10.dylib ??? (???)
<b4fb0c115a66217830b00c619b922bb8> /opt/local/lib/libgmp.10.dylib
  0x1f0000 -   0x22bfff +libncurses.5.dylib ??? (???)
<d81bafd2d6d61538fff66b23dc9c8a56> /opt/local/lib/libncurses.5.dylib
  0x23b000 -   0x23dfff +libsigsegv.2.dylib ??? (???)
<1075d4662269e61297223cb414cf8162> /opt/local/lib/libsigsegv.2.dylib
0x8fe00000 - 0x8fe30c23  dyld 97.1 (???) <89a0055b0e7ea2db881b73c6e63bc774>
/usr/lib/dyld
0x90003000 - 0x9000bfff  libbsm.dylib ??? (???)
<c1fca3cbe3b1c21e9b31bc89b920f34c> /usr/lib/libbsm.dylib
0x91663000 - 0x91736fff  com.apple.CoreServices.OSServices 228.1 (228.1)
<b957e9c8b8ca9c3e03b99d2ad4b31aa2>
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
0x918fb000 - 0x91980fff  libsqlite3.0.dylib ??? (???)
<daf55b073488086ef5b9a3781be53f14> /usr/lib/libsqlite3.0.dylib
0x91987000 - 0x91aacff3  com.apple.CoreFoundation 6.5.7 (476.19)
<dee0f0024f3bf976cfa0a0816e8aa338>
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
0x91ae2000 - 0x91b01fff  libresolv.9.dylib ??? (???)
<c5c72e1cf61cb844163156956a1d8407> /usr/lib/libresolv.9.dylib
0x91ee9000 - 0x91f9cffc  com.apple.CFNetwork 438.16 (438.16)
<a5b69f31ef4596c8f680772120e3eb08>
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
0x91f9d000 - 0x91fecfff  com.apple.Metadata 10.5.8 (398.26)
<1a261534027b9d1518327d1fabe1182b>
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
0x922bb000 - 0x92336fff  com.apple.SearchKit 1.2.2 (1.2.2)
<a9d0033a5e1e55b5e382e52fe578d734>
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
0x92a88000 - 0x92a8dff6  libmathCommon.A.dylib ??? (???)
/usr/lib/system/libmathCommon.A.dylib
0x92bc3000 - 0x92beeff7  libauto.dylib ??? (???)
<a64d088b2d17e013b9ee5a08d3a20d33> /usr/lib/libauto.dylib
0x92bfa000 - 0x92c2ffff  com.apple.AE 402.3 (402.3)
<75725936d014fd3ca2553d18b784b99b>
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
0x92cb9000 - 0x92cc4ffb  libgcc_s.1.dylib ??? (???)
<ea47fd375407f162c76d14d64ba246cd> /usr/lib/libgcc_s.1.dylib
0x92d84000 - 0x93086ffb  com.apple.CoreServices.CarbonCore 786.16 (786.16)
<d9a357a3be5a1bf5969e80db6a4b3327>
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
0x93087000 - 0x9316afff  libobjc.A.dylib ??? (???)
<a1d4be2eed463c6799b6a1447fde72ba> /usr/lib/libobjc.A.dylib
0x93c94000 - 0x93cacffb  com.apple.DictionaryServices 1.0.0 (1.0.0)
<fe37191e732eeb66189185cd000a210b>
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
0x93db7000 - 0x93dc0fff  com.apple.DiskArbitration 2.2.1 (2.2.1)
<682f5c45591e8c4a89c79e384e2c49af>
/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
0x93f63000 - 0x940abff3  libicucore.A.dylib ??? (???)
<bdab570d90979c4f601131d442f84720> /usr/lib/libicucore.A.dylib
0x94b51000 - 0x94be6ff7  com.apple.framework.IOKit 1.5.2 (???)
<ced0a498252f76a2d2ba9f2a0ae02160>
/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x94c4b000 - 0x94c84fff  com.apple.SystemConfiguration 1.9.2 (1.9.2)
<21dee7ffd93306032f911b5ef3fdbab3>
/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
0x95e6a000 - 0x95e6affa  com.apple.CoreServices 32 (32)
<42b6dda539f7411606187335d9eae0c5>
/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
0x95e76000 - 0x95f0dfff  com.apple.LaunchServices 292 (292)
<06cb373fd960fbc2b4a0201f55c7dd6d>
/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
0x96334000 - 0x9641efff  libxml2.2.dylib ??? (???)
<9d05a5451084c8cd78e3f4722e2c2960> /usr/lib/libxml2.2.dylib
0x96ed8000 - 0x97078fe3  libSystem.B.dylib ??? (???)
<7dc28e19e1aac16b29cbd7c5d9ce9638> /usr/lib/libSystem.B.dylib
0x978e5000 - 0x9794cffb  libstdc++.6.dylib ??? (???)
<a4e9b10268b3ffac26d0296499b24e8e> /usr/lib/libstdc++.6.dylib
0x9794d000 - 0x9795bfff  libz.1.dylib ??? (???)
<1a70dd3594a8c5ad39d785af5da23237> /usr/lib/libz.1.dylib
0x97979000 - 0x97b62ffb  com.apple.security 5.0.7 (1)
<2c8ae7414f8d113a695da92950753ad9>
/System/Library/Frameworks/Security.framework/Versions/A/Security
0x97b63000 - 0x97b8bfff  libxslt.1.dylib ??? (???)
<82421418f81b9b6c63529215a3612ab0> /usr/lib/libxslt.1.dylib
0xfffec000 - 0xfffeffff  libobjc.A.dylib ??? (???) /usr/lib/libobjc.A.dylib
0xffff8000 - 0xffff9703  libSystem.B.dylib ??? (???)
/usr/lib/libSystem.B.dylib

On Mon, Oct 7, 2013 at 11:47 AM, cgyarvin notifications@github.com wrote:

> Ooh that's a G4. Never tried it on one... Can you get a stack trace tho?
> 
> Sent from my iPhone
> 
> On Oct 6, 2013, at 5:58 PM, davids99us notifications@github.com wrote:
> 
> > David-Stockwells-Computer-2:urbit-master davids$ bin/vere -c mypier
> > vere: urbit home is /Users/davids/urbit-master/urb
> > loom: mapped 1024MB
> > time: ~2013.10.7..01.45.52..badb
> > ames: on localhost, UDP 49653.
> > http: live on 8080
> > generating 2048-bit RSA pair...
> > address 0x0 out of loom!
> > Segmentation fault
> > David-Stockwells-Computer-2:urbit-master davids$
> > 
> > Mac OSX 10.5.8
> > 1.67 GHz Power PC G4
> > 1 GB mem
> > 
> > All good with macports install up to there.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/urbit/urbit/issues/52#issuecomment-25781624
> .

## 

Dr David R.B. Stockwell

Like us at http://facebook.com/deepfeetmassagetherapy

**Comment by cgyarvin** [comment]
Hm.  I'm tempted to call that a libuv bug - it's certainly dying in libuv, and it wouldn't surprise me at all if that OS version is too old...

**Comment by davids99us** [comment]
I think there was a good reason I didn't upgrade - like the PowerPC was no
longer supported.  Still its worth chasing up segfaults generally.

On Mon, Oct 7, 2013 at 1:13 PM, cgyarvin notifications@github.com wrote:

> Hm. I'm tempted to call that a libuv bug - it's certainly dying in libuv,
> and it wouldn't surprise me at all if that OS version is too old...
> 
> Sent from my iPhone
> 
> On Oct 6, 2013, at 7:11 PM, davids99us notifications@github.com wrote:
> 
> > Is this it?
> > 
> > Process: vere [23401]
> > Path: bin/vere
> > Identifier: vere
> > Version: ??? (???)
> > Code Type: PPC (Native)
> > Parent Process: bash [23054]
> > 
> > Date/Time: 2013-10-07 11:46:29.761 +1000
> > OS Version: Mac OS X 10.5.8 (9L31a)
> > Report Version: 6
> > Anonymous UUID: DF8ABA10-81FF-41EF-A81F-2550204ED487
> > 
> > Exception Type: EXC_CRASH (SIGSEGV)
> > Exception Codes: 0x0000000000000000, 0x0000000000000000
> > Crashed Thread: 0
> > 
> > Thread 0 Crashed:
> > 0 libSystem.B.dylib 0x96f5a9f0 __kill + 12
> > 1 libsigsegv.2.dylib 0x0023d800 terminating_handler + 16
> > 2 libSystem.B.dylib 0x96f153bc realpath$DARWIN_EXTSN + 152
> > 3 vere 0x0006bd3c uv__fsevents_init + 88
> > (fsevents.c:221)
> > 4 vere 0x0006b4a8 uv_fs_event_init + 488
> > (kqueue.c:321)
> > 5 vere 0x0000f980 _unix_hot_gain + 272
> > 6 vere 0x0000fa14 u2_unix_ef_init + 52
> > 7 vere 0x00009e14 u2_reck_kick + 1652
> > 8 vere 0x00005c24 _lo_sure + 308
> > 9 vere 0x00006aa4 _lo_work + 756
> > 10 vere 0x00007b44 u2_lo_loop + 676
> > 11 vere 0x000088f8 main + 1944
> > 12 vere 0x00002560 start + 64
> > 
> > Thread 1:
> > 0 libSystem.B.dylib 0x96ed9078 mach_msg_trap + 8
> > 1 libSystem.B.dylib 0x96edff9c mach_msg + 56
> > 2 libsigsegv.2.dylib 0x0023d570 mach_exception_thread + 76
> > 3 libSystem.B.dylib 0x96f1af70 _pthread_start + 316
> > 
> > Thread 2:
> > 0 libSystem.B.dylib 0x96ed9078 mach_msg_trap + 8
> > 1 libSystem.B.dylib 0x96edff9c mach_msg + 56
> > 2 com.apple.CoreFoundation 0x919f0394 CFRunLoopRunSpecific + 1812
> > 3 com.apple.CoreFoundation 0x919f0c1c CFRunLoopRun + 60
> > 4 vere 0x00069244 uv__cf_loop_runner + 132
> > (darwin.c:119)
> > 5 vere 0x0006771c uv__thread_start + 80
> > 6 libSystem.B.dylib 0x96f1af70 _pthread_start + 316
> > 
> > Thread 0 crashed with PPC Thread State 32:
> > srr0: 0x96f5a9f0 srr1: 0x0000d030 dar: 0xf0102ee4 dsisr: 0x42000000
> > r0: 0x00000025 r1: 0xbfffa670 r2: 0x0000008d r3: 0x00000000
> > r4: 0x00000000 r5: 0x00000001 r6: 0x2d746963 r7: 0x64656d00
> > r8: 0xffb68180 r9: 0x00000000 r10: 0xffffffc1 r11: 0xa0b1052c
> > r12: 0x96f5a9dc r13: 0x00000000 r14: 0x00000000 r15: 0xbfffc4e8
> > r16: 0x000778b0 r17: 0x000778b0 r18: 0x00000000 r19: 0x00000000
> > r20: 0x000867c0 r21: 0x0012a670 r22: 0x00000000 r23: 0x8216af7d
> > r24: 0x0007f880 r25: 0x00000000 r26: 0x00497ca0 r27: 0x00497ca1
> > r28: 0x0012a044 r29: 0x00497db0 r30: 0x00497e80 r31: 0x96f15338
> > cr: 0x42000222 xer: 0x00000004 lr: 0x0023d804 ctr: 0x96f5a9dc
> > vrsave: 0x00000000
> > 
> > Binary Images:
> > 0x1000 - 0x74ff3 +vere ??? (???) <3c05ca9e2d705bcc78367cba005a89d9>
> > /Users/davids/urbit-master/bin/vere
> > 0x189000 - 0x1e0fef +libgmp.10.dylib ??? (???)
> > <b4fb0c115a66217830b00c619b922bb8> /opt/local/lib/libgmp.10.dylib
> > 0x1f0000 - 0x22bfff +libncurses.5.dylib ??? (???)
> > <d81bafd2d6d61538fff66b23dc9c8a56> /opt/local/lib/libncurses.5.dylib
> > 0x23b000 - 0x23dfff +libsigsegv.2.dylib ??? (???)
> > <1075d4662269e61297223cb414cf8162> /opt/local/lib/libsigsegv.2.dylib
> > 0x8fe00000 - 0x8fe30c23 dyld 97.1 (???)
> > <89a0055b0e7ea2db881b73c6e63bc774>
> > /usr/lib/dyld
> > 0x90003000 - 0x9000bfff libbsm.dylib ??? (???)
> > <c1fca3cbe3b1c21e9b31bc89b920f34c> /usr/lib/libbsm.dylib
> > 0x91663000 - 0x91736fff com.apple.CoreServices.OSServices 228.1 (228.1)
> > <b957e9c8b8ca9c3e03b99d2ad4b31aa2>
> > 
> > /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
> > 
> > 0x918fb000 - 0x91980fff libsqlite3.0.dylib ??? (???)
> > <daf55b073488086ef5b9a3781be53f14> /usr/lib/libsqlite3.0.dylib
> > 0x91987000 - 0x91aacff3 com.apple.CoreFoundation 6.5.7 (476.19)
> > <dee0f0024f3bf976cfa0a0816e8aa338>
> > 
> > /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
> > 
> > 0x91ae2000 - 0x91b01fff libresolv.9.dylib ??? (???)
> > <c5c72e1cf61cb844163156956a1d8407> /usr/lib/libresolv.9.dylib
> > 0x91ee9000 - 0x91f9cffc com.apple.CFNetwork 438.16 (438.16)
> > <a5b69f31ef4596c8f680772120e3eb08>
> > 
> > /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
> > 
> > 0x91f9d000 - 0x91fecfff com.apple.Metadata 10.5.8 (398.26)
> > <1a261534027b9d1518327d1fabe1182b>
> > 
> > /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
> > 
> > 0x922bb000 - 0x92336fff com.apple.SearchKit 1.2.2 (1.2.2)
> > <a9d0033a5e1e55b5e382e52fe578d734>
> > 
> > /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
> > 
> > 0x92a88000 - 0x92a8dff6 libmathCommon.A.dylib ??? (???)
> > /usr/lib/system/libmathCommon.A.dylib
> > 0x92bc3000 - 0x92beeff7 libauto.dylib ??? (???)
> > <a64d088b2d17e013b9ee5a08d3a20d33> /usr/lib/libauto.dylib
> > 0x92bfa000 - 0x92c2ffff com.apple.AE 402.3 (402.3)
> > <75725936d014fd3ca2553d18b784b99b>
> > 
> > /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
> > 
> > 0x92cb9000 - 0x92cc4ffb libgcc_s.1.dylib ??? (???)
> > <ea47fd375407f162c76d14d64ba246cd> /usr/lib/libgcc_s.1.dylib
> > 0x92d84000 - 0x93086ffb com.apple.CoreServices.CarbonCore 786.16
> > (786.16)
> > <d9a357a3be5a1bf5969e80db6a4b3327>
> > 
> > /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
> > 
> > 0x93087000 - 0x9316afff libobjc.A.dylib ??? (???)
> > <a1d4be2eed463c6799b6a1447fde72ba> /usr/lib/libobjc.A.dylib
> > 0x93c94000 - 0x93cacffb com.apple.DictionaryServices 1.0.0 (1.0.0)
> > <fe37191e732eeb66189185cd000a210b>
> > 
> > /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
> > 
> > 0x93db7000 - 0x93dc0fff com.apple.DiskArbitration 2.2.1 (2.2.1)
> > <682f5c45591e8c4a89c79e384e2c49af>
> > 
> > /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
> > 
> > 0x93f63000 - 0x940abff3 libicucore.A.dylib ??? (???)
> > <bdab570d90979c4f601131d442f84720> /usr/lib/libicucore.A.dylib
> > 0x94b51000 - 0x94be6ff7 com.apple.framework.IOKit 1.5.2 (???)
> > <ced0a498252f76a2d2ba9f2a0ae02160>
> > /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
> > 0x94c4b000 - 0x94c84fff com.apple.SystemConfiguration 1.9.2 (1.9.2)
> > <21dee7ffd93306032f911b5ef3fdbab3>
> > 
> > /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
> > 
> > 0x95e6a000 - 0x95e6affa com.apple.CoreServices 32 (32)
> > <42b6dda539f7411606187335d9eae0c5>
> > 
> > /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
> > 0x95e76000 - 0x95f0dfff com.apple.LaunchServices 292 (292)
> > <06cb373fd960fbc2b4a0201f55c7dd6d>
> > 
> > /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
> > 
> > 0x96334000 - 0x9641efff libxml2.2.dylib ??? (???)
> > <9d05a5451084c8cd78e3f4722e2c2960> /usr/lib/libxml2.2.dylib
> > 0x96ed8000 - 0x97078fe3 libSystem.B.dylib ??? (???)
> > <7dc28e19e1aac16b29cbd7c5d9ce9638> /usr/lib/libSystem.B.dylib
> > 0x978e5000 - 0x9794cffb libstdc++.6.dylib ??? (???)
> > <a4e9b10268b3ffac26d0296499b24e8e> /usr/lib/libstdc++.6.dylib
> > 0x9794d000 - 0x9795bfff libz.1.dylib ??? (???)
> > <1a70dd3594a8c5ad39d785af5da23237> /usr/lib/libz.1.dylib
> > 0x97979000 - 0x97b62ffb com.apple.security 5.0.7 (1)
> > <2c8ae7414f8d113a695da92950753ad9>
> > /System/Library/Frameworks/Security.framework/Versions/A/Security
> > 0x97b63000 - 0x97b8bfff libxslt.1.dylib ??? (???)
> > <82421418f81b9b6c63529215a3612ab0> /usr/lib/libxslt.1.dylib
> > 0xfffec000 - 0xfffeffff libobjc.A.dylib ??? (???)
> > /usr/lib/libobjc.A.dylib
> > 0xffff8000 - 0xffff9703 libSystem.B.dylib ??? (???)
> > /usr/lib/libSystem.B.dylib
> > 
> > On Mon, Oct 7, 2013 at 11:47 AM, cgyarvin notifications@github.com
> > wrote:
> > 
> > > Ooh that's a G4. Never tried it on one... Can you get a stack trace
> > > tho?
> > > 
> > > Sent from my iPhone
> > > 
> > > On Oct 6, 2013, at 5:58 PM, davids99us notifications@github.com
> > > wrote:
> > > 
> > > > David-Stockwells-Computer-2:urbit-master davids$ bin/vere -c mypier
> > > > vere: urbit home is /Users/davids/urbit-master/urb
> > > > loom: mapped 1024MB
> > > > time: ~2013.10.7..01.45.52..badb
> > > > ames: on localhost, UDP 49653.
> > > > http: live on 8080
> > > > generating 2048-bit RSA pair...
> > > > address 0x0 out of loom!
> > > > Segmentation fault
> > > > David-Stockwells-Computer-2:urbit-master davids$
> > > > 
> > > > Mac OSX 10.5.8
> > > > 1.67 GHz Power PC G4
> > > > 1 GB mem
> > > > 
> > > > All good with macports install up to there.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/urbit/urbit/issues/52#issuecomment-25781624>
> > > .
> > 
> > ## 
> > 
> > Dr David R.B. Stockwell
> > 
> > Like us at http://facebook.com/deepfeetmassagetherapy
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/urbit/urbit/issues/52#issuecomment-25783253
> .

## 

Dr David R.B. Stockwell

Like us at http://facebook.com/deepfeetmassagetherapy
