### ISSUE TITLE
^C not working until reboot of server

### ISSUE THREAD

**Issue by pgray** [urbit/archaeology#53]
I am not sure how to describe the issue much more than the title.

Basically hitting ^C after executing :begin doesn't work until I've hit ^D and then run vere on my pier again.

After running vere, ^X will switch me back to the :begin process and then only can I kill it.

**Comment by SethTisue** [comment]
I believe I experienced this as well. When working through the tutorial for the first time, ^C didn't work. Now, in subsequent `vere` runs (without rebuilding urbit or anything like that), it works fine.

**Comment by cgyarvin** [comment]
Something is getting messed up with the signal handling, I think.
 Unfortunately a low priority...

**Comment by ghost** [comment]
Dupe of #102, fixed hopefully by the same.
