### ISSUE TITLE
:ram example from chapter 1 is broken

### ISSUE THREAD

**Issue by dhaffey** [urbit/archaeology#57]
The example from chapter 1

```
:ram /===/doc/fortytwo/noun; (mul 6 7)
```

fails when calling the non-existent `file` function. Stack trace snippet:

```
! /~ladhut-docfyn/ram/bin/~2013.10.16..01.33.23..d362/main:<[36 14].[36 18]>
! -find-limb.file
```

**Comment by kingdonb** [comment]
This example still doesn't work, though it's been moved to [arvo/tut/2](http://urbit.org/doc/arvo/tut/2)

I am also wondering how to use the output of eg. gen.hoon in another hoon app, `:type`, or cast it to some other odor than `@uw`:

```
:=try=/bin/gen :=main=/bin/ram /===test/gen/noun
:=main=/bin/ram /===/test/gen/noun; 5
```

I think both of these are syntactically correct in batz but I get this (different than before) syntax error:

```
! /~zod/arvo/~2014.4.25..17.21.41..5dbe/batz/:<[1.130 7].[1.137 59]>
! /~zod/arvo/~2014.4.25..17.21.41..5dbe/batz/:<[1.131 7].[1.137 59]>
! /~zod/arvo/~2014.4.25..17.21.41..5dbe/batz/:<[1.132 7].[1.137 59]>
! /~zod/arvo/~2014.4.25..17.21.41..5dbe/batz/:<[1.133 7].[1.137 59]>
! /~zod/arvo/~2014.4.25..17.21.41..5dbe/batz/:<[1.134 7].[1.137 59]>
! /~zod/arvo/~2014.4.25..17.21.41..5dbe/batz/:<[1.135 7].[1.137 59]>
! /~zod/arvo/~2014.4.25..17.21.41..5dbe/batz/:<[1.136 7].[1.137 59]>
! /~simmev-rabryd/main/~2014.4.30..15.31.14..389c/bin/ram/hoon
! /~zod/arvo/~2014.4.25..17.21.41..5dbe/batz/:<[1.137 7].[1.137 59]>
! {42 4}
! 'syntax-error'
! exit
```

I think this indicates a syntax error in ram.hoon?  42.4 is the end of the unnamed arm in `%=  $` &mdash; is that right?

I would also like to have some way to

```
`@p`; :=try=/bin/gen
```

inside of the batz shell...

**Comment by cgyarvin** [comment]
Yeah, there's always a part of Urbit for which bugs live too long because
they're waiting on a rewrite.  Today, this is %batz - and associated
utilities, like :ram.

The whole user-level application interface (bowl, gift, slip, etc) is
changing to be more like the kernel-level application interface (++vane).
 And in particular, having the shell in %batz itself is sort of like having
/bin/sh in /vmlinux.  Ie, not a good idea.

**Comment by cgyarvin** [comment]
Am I at least using it correctly, if it was in working condition

Is there a syntax for executing a hoon app and using its output in a hoon 
expression?  Closest I found was that ^:@/ thing in Arvo Pt.2

:gen :ram /===/test/noun/uw
should work on its own (right) or is there some semantic difference between 
returning and outputting that I've neglected to take account for...

Is this the right approach to casting :gen's `@uw` output value to another 
odor, or should it be possible without altering gen and without ram'ing 
anything into clay?

--Kingdon

**Comment by cgyarvin** [comment]
On Wed, Apr 30, 2014 at 11:20 AM, yebyen yebyen@gmail.com wrote:

> Is there a syntax for executing a hoon app and using its output in a hoon
> expression?

Juxtaposition:

,@p :gen

**Comment by kingdonb** [comment]
Aww yeah, sweet.  Thanks

**Comment by cgyarvin** [comment]
That seems to work only in the one case I presented...

What about these:
~simmev-rabryd/king=> ,@p :=try=/bin/gen
~taglup-somput-mipmev-tannyd--bacrut-ponhes-dopmet-tonsul--dardun-danpet-famteg-tandeg--winlec-marbud-hidrux-hopwen
~simmev-rabryd/king=> ,@ux :=try=/bin/gen
0x75b2.1c5c.8b80.2dc7.3ac4.0bce.762f.8c21.1cff.aeb7.5f5e.5926.51a4.e2d5.a7e5.6d3f
~simmev-rabryd/king=> test=,@ux :=try=/bin/gen
! -find-limb.$
! find-none
! exit
~simmev-rabryd/king=> =test ,@ux :=try=/bin/gen
~ <syntax error at [1 13]>
~simmev-rabryd/king=> (add 1 ,@ud :=try=/bin/gen)
~ <syntax error at [1 14]>
~simmev-rabryd/king=> (add 1 ,:=try=/bin/gen)
~ <syntax error at [1 9]>
