### ISSUE TITLE
Wiki Pull Request: add subdirectories

### ISSUE THREAD

**Issue by abliss** [urbit/archaeology#66]
[Github does not support PRs for wiki context, so I'm doing this instead.]

I would like you to merge the master branch of git@github.com:abliss/urbit.wiki.git into the master branch of git@github.com:urbit/urbit.wiki.git . This should be a fast-forward merge.

I have moved the autogenerated rune pages, the autogenerated hoon-function pages, and my own Decoding Hoon document to their own subdirectories. This makes the repo a bit cleaner, and also allows the usage of different Sidebars in the documents. (I wanted to be able to add a Cheat Sheet sidebar to my Decoding Hoon journal.)

If you have comments on this pull request, feel free to leave them here and I will address them.

Thanks.

**Comment by PhaseMage** [comment]
I've just been updating the urbit wiki directly. Will my edits make the merge more difficult? Should I try to move my edits over to your (abliss) branch, and just work on it there until we can get your subdirectory change moved up to the master urbit wiki?

**Comment by abliss** [comment]
Nah, editing directly upstream is best for changes which don't require git. I'll continue to rebase this PR on top of your edits until it is closed.

**Comment by ericfode** [comment]
Merged!!

**Comment by ericfode** [comment]
This is pretty awesome! Nice job :+1:
