### ISSUE TITLE
vere: v/unix.c:553: _unix_load: Assertion `0' failed.

### ISSUE THREAD

**Issue by mrdomino** [urbit/archaeology#94]
This happened while messing with files in /=try=. I removed a file shortly after an update, saw "/home/tux/urbit/urb/macmud-taprut/try/bin/foo.hoon: No such file or directory", then that assert failure.

**Comment by cgyarvin** [comment]
Yeah I've seen that.  I know pretty much why it happens, too.  But assert
fails are fairly low priority for us because, you know, no data is lost,
and it also happens while you're fscking around with the system so you see
it right away...

**Comment by ghost** [comment]
As of 9122d1c63d78aee6d4a7a4924bcb229bccd96cbc we just ignore files that go missing between the notification and the load.
